using AutoVeritas.OffersService.Models;

namespace AutoVeritas.OffersService.Seeding;

/// <summary>
/// The August 2026 verification pass over the Spanish market (Alicante / Madrid ZBE
/// focus), as researched and verified by the owner's agent. This file answers "what
/// does a fresh environment get"; the database answers "what runs here" — the seeder
/// inserts by slug and never overwrites, so later agent edits always win.
///
/// The timestamps are real data, not code metadata: LastVerifiedAt is when the agent
/// checked the value at source, OfferValidUntil is the seller's declared validity
/// (BYD promotions ran to 31/08/2026, Tesla financing to 30/09/2026), and
/// SourcePublishedAt is the source's own publication date when it differs from the
/// verification date.
///
/// Seller deadlines carry the Spanish market's +02:00 offset — "valid until 31/08"
/// means the end of that day in Spain, and rendering or expiring it as a UTC
/// midnight would move the deadline by a day.
/// </summary>
public static class SeedData
{
    private static readonly DateTimeOffset VerifiedAugust24 = new(2026, 8, 24, 12, 0, 0, TimeSpan.Zero);

    // Stored as UTC (Npgsql accepts only offset zero) but defined as the Spanish
    // end-of-day instant, so the deadline neither renders nor expires a day off.
    private static readonly DateTimeOffset BydOffersEnd =
        new DateTimeOffset(2026, 8, 31, 23, 59, 59, TimeSpan.FromHours(2)).ToUniversalTime();
    private static readonly DateTimeOffset TeslaOffersEnd =
        new DateTimeOffset(2026, 9, 30, 23, 59, 59, TimeSpan.FromHours(2)).ToUniversalTime();

    public static IReadOnlyList<CarOffer> CarOffers() =>
    [
        Car("tesla-model-3-rwd", "Tesla Model 3 Tracción trasera", "Sedan / BEV", DgtLabel.Cero, 283,
            cash: 33365, financed: null, reliability: 89, "Wysoka", boot: 682,
            "Powyżej budżetu nawet przy najlepszej cenie gotówkowej",
            Confidence.Confirmed, "tesla.com/es_es", "https://www.tesla.com/es_es/model3/design",
            validUntil: TeslaOffersEnd),
        Car("tesla-model-y-rwd", "Tesla Model Y Tracción trasera", "SUV / BEV", DgtLabel.Cero, 299,
            cash: 40760, financed: null, reliability: 89, "Wysoka", boot: 854,
            "Znacznie powyżej budżetu; najtańsze obecnie finansowanie Tesli",
            Confidence.Confirmed, "tesla.com/es_es", "https://www.tesla.com/es_es/modely/design",
            validUntil: TeslaOffersEnd),
        Car("byd-atto-2-dm-i-active", "BYD Atto 2 DM-i Active", "SUV / PHEV", DgtLabel.Cero, 166,
            cash: 25990, financed: 20940, reliability: 89, "Wysoka", boot: 425,
            "TOP PICK — etykieta CERO, realna cena poniżej 30k gotówką",
            Confidence.Confirmed, "byd.com/es", "https://www.byd.com/es/car/atto2",
            validUntil: BydOffersEnd),
        Car("byd-atto-2-dm-i-boost", "BYD Atto 2 DM-i Boost", "SUV / PHEV", DgtLabel.Cero, 212,
            cash: 31200, financed: 24940, reliability: 89, "Wysoka", boot: 425,
            "90 km zasięgu EV, kamera 360°, panoramiczny dach",
            Confidence.Confirmed, "byd.com/es", "https://www.byd.com/es/car/atto2",
            validUntil: BydOffersEnd),
        Car("byd-dolphin-surf-active", "BYD Dolphin Surf Active", "Hatchback / BEV", DgtLabel.Cero, 95,
            cash: 18780, financed: 12955, reliability: 89, "Wysoka", boot: null,
            "Miejski EV, zasięg 220 km",
            Confidence.Confirmed, "byd.com/es", "https://www.byd.com/es/car/dolphinsurf",
            validUntil: BydOffersEnd),
        Car("byd-dolphin-surf-comfort", "BYD Dolphin Surf Comfort", "Hatchback / BEV", DgtLabel.Cero, 156,
            cash: 26490, financed: null, reliability: 89, "Wysoka", boot: null,
            "310 km WLTP",
            Confidence.Confirmed, "byd.com/es", "https://www.byd.com/es/car/dolphinsurf",
            validUntil: BydOffersEnd),
        Car("mg4-urban", "MG4 Urban", "Hatchback / BEV", DgtLabel.Cero, 170,
            cash: null, financed: 16790, reliability: 72, "Średnia", boot: null,
            "Najtańszy EV na liście; słabsza niezawodność",
            Confidence.Confirmed, "mg.es", "https://www.mg.es/mg4"),
        Car("mg4-64-kwh", "MG4 64 kWh", "Hatchback / BEV", DgtLabel.Cero, 204,
            cash: null, financed: 27065, reliability: 72, "Średnia", boot: null,
            "Wariant o dłuższym zasięgu",
            Confidence.Confirmed, "mg.es", "https://www.mg.es/mg4"),
        Car("vw-id3-neo", "VW ID.3 Neo", "Hatchback / BEV", DgtLabel.Cero, 170,
            cash: null, financed: 29495, reliability: 80, "Dobra", boot: null,
            "Europejska produkcja; blisko granicy budżetu (przed Plan Auto+)",
            Confidence.Confirmed, "volkswagen.es", "https://www.volkswagen.es/es/modelos/id3.html"),
        Car("omoda-5-shs-h", "Omoda 5 SHS-H", "SUV / HEV", DgtLabel.Eco, 224,
            cash: 29400, financed: 23640, reliability: 60, "Niesprawdzona", boot: null,
            "7-letnia gwarancja; lokalny dealer w Alicante",
            Confidence.Confirmed, "omodajaecoo.es", "https://www.omodajaecoo.es/omoda-5"),
        Car("mg-zs-hybrid-plus", "MG ZS Hybrid+", "SUV / HEV", DgtLabel.Eco, 195,
            cash: 22590, financed: 20090, reliability: 72, "Średnia", boot: null,
            "Najtańszy hybrydowy SUV",
            Confidence.Confirmed, "mg.es", "https://www.mg.es/mg-zs-hybrid"),
        Car("toyota-yaris-cross", "Toyota Yaris Cross", "B-SUV / HEV", DgtLabel.Eco, 130,
            cash: 27500, financed: 26400, reliability: 91, "Bardzo wysoka", boot: null,
            "Wzorcowa niezawodność; droższe finansowanie (7,5–7,75% TIN)",
            Confidence.Confirmed, "toyota.es", "https://www.toyota.es/coches/yaris-cross"),
        Car("kia-niro-hybrid", "Kia Niro Hybrid", "C-SUV / HEV", DgtLabel.Eco, 138,
            cash: 28434, financed: 24410, reliability: 85, "Wysoka", boot: 451,
            "7-letnia gwarancja; silny stosunek jakości do ceny",
            Confidence.Confirmed, "kia.com/es", "https://www.kia.com/es/modelos/niro"),
        Car("hyundai-kona-hybrid", "Hyundai Kona Hybrid", "SUV / HEV", DgtLabel.Eco, 141,
            cash: null, financed: 26540, reliability: 85, "Wysoka", boot: null,
            "5-letnia gwarancja",
            Confidence.Confirmed, "hyundai.es", "https://www.hyundai.es/modelos/kona-hybrid"),
        Car("renault-symbioz-e-tech", "Renault Symbioz E-Tech", "SUV / HEV", DgtLabel.Eco, 160,
            cash: 30120, financed: 27026, reliability: 78, "Dobra", boot: 548,
            "Produkcja w Valladolid, Hiszpania",
            Confidence.Confirmed, "renault.es", "https://www.renault.es/coches-hibridos/symbioz.html"),
        Car("renault-arkana-e-tech", "Renault Arkana E-Tech", "SUV / HEV", DgtLabel.Eco, 152,
            cash: 31383, financed: 26400, reliability: 78, "Dobra", boot: null,
            "Model wycofywany — sprawdź dostępność",
            Confidence.Confirmed, "renault.es", "https://www.renault.es/coches-hibridos/arkana.html"),
        Car("cupra-born-base", "Cupra Born (base)", "Hatchback / BEV", DgtLabel.Cero, 170,
            cash: 37990, financed: 33500, reliability: 76, "Średnia", boot: null,
            "Poza budżetem — dane kontekstowe",
            Confidence.Confirmed, "cupraofficial.es", "https://www.cupraofficial.es/coches/born"),
    ];

    public static IReadOnlyList<FinancingOffer> FinancingOffers() =>
    [
        Fin("bankinter-consumer-finance", "Bankinter Consumer Finance", FinancingType.Bank,
            tin: 4.45m, tae: 4.54m, RepaymentStructure.Linear, "do 120 mies.", "Brak wymaganej",
            "Brak opłaty za otwarcie", monthly: 484, interest: 3050,
            "Najlepszy uniwersalny wybór — dowolna marka, bez ograniczeń",
            Confidence.Confirmed, "Rastreator", "https://www.rastreator.com/prestamos/coche"),
        Fin("fintonic", "Fintonic", FinancingType.Bank,
            tin: 4.54m, tae: 4.60m, RepaymentStructure.Linear, "Zmienny", "Brak",
            "Niskie", monthly: 486, interest: 3120,
            "Bliski konkurent Bankintera — top 2 wg Rastreator sierpień 2026",
            Confidence.Confirmed, "Rastreator", "https://www.rastreator.com/prestamos/coche"),
        Fin("bbva-coche-ecologico", "Kredyt 'zielony' — BBVA Coche Ecológico", FinancingType.Green,
            tin: 3.75m, tae: 3.95m, RepaymentStructure.Linear, "do 8 lat", "Zmienna",
            "Niższe niż standardowy kredyt", monthly: 470, interest: 2650,
            "Tylko dla aut ECO/CERO — realnie 0,5–3% TAE taniej niż kredyt standardowy",
            Confidence.Estimated, "bbva.es", "https://www.bbva.es/personas/prestamos/coche.html"),
        Fin("caixabank-auto-eco", "Kredyt 'zielony' — CaixaBank Auto Eco", FinancingType.Green,
            tin: 3.90m, tae: 4.10m, RepaymentStructure.Linear, "do 8 lat",
            "Zmienna, niższa przy wiązaniu produktów", "Często brak opłaty otwarcia",
            monthly: 475, interest: 2700,
            "Wymaga etykiety ECO/CERO; oszczędność rośnie z kwotą 20-30k €",
            Confidence.Estimated, "caixabank.es", "https://www.caixabank.es/particular/prestamos/prestamo-eco.html"),
        Fin("kutxabank-auto-sostenible", "Kredyt 'zielony' — Kutxabank Auto Sostenible", FinancingType.Green,
            tin: 4.10m, tae: 4.30m, RepaymentStructure.Linear, "do 8 lat", "Zmienna",
            "Standardowe", monthly: 480, interest: 2800,
            "Alternatywa regionalna dla aut elektrycznych/hybrydowych",
            Confidence.Estimated, "kutxabank.es", "https://www.kutxabank.es"),
        Fin("revolut", "Revolut", FinancingType.Fintech,
            tin: 3.49m, tae: 3.60m, RepaymentStructure.Linear, "do 8 lat", "Brak",
            "Brak opłat", monthly: 462, interest: 2450,
            "Najniższy TIN w zestawieniu — do 30 000 € w pełni online",
            Confidence.Confirmed, "revolut.com/es", "https://www.revolut.com/es-ES/prestamos"),
        Fin("n26", "N26", FinancingType.Fintech,
            tin: 3.99m, tae: 4.06m, RepaymentStructure.Linear, "do 60 mies. (1–5 lat)", "Brak",
            "Brak", monthly: 470, interest: 2660,
            "Szybki proces w aplikacji; limit do 15 000 € — dla mniejszych dopłat",
            Confidence.Confirmed, "n26.com/es", "https://n26.com/es-es/credito"),
        Fin("cofidis-auto", "Cofidis Auto", FinancingType.Fintech,
            tin: 5.75m, tae: 5.99m, RepaymentStructure.Linear, "Zmienny", "Brak",
            "Bez zmiany banku", monthly: 502, interest: 3980,
            "Bankkers wskazuje jako najtańszy niezależny — porównaj z Bankinter/Revolut",
            Confidence.Confirmed, "cofidis.es", "https://www.cofidis.es/es/creditos/coche.html"),
        Fin("bankintercard", "Bankintercard", FinancingType.Fintech,
            tin: 4.45m, tae: 4.60m, RepaymentStructure.Linear, "Zmienny", "Brak",
            "0% prowizji otwarcia online", monthly: 484, interest: 3100,
            "Wariant kartowy Bankintera — 100% online",
            Confidence.Confirmed, "bankintercard.es", "https://www.bankintercard.es"),
        Fin("tesla-caixabank-model-3", "Tesla / Caixabank (Model 3)", FinancingType.Manufacturer,
            tin: 5.75m, tae: 5.90m, RepaymentStructure.Balloon, "do 84 mies.", "Zmienna",
            "Standardowe", monthly: 503, interest: 4100,
            "Już niekonkurencyjne — wcześniej było 1,99–2,01%",
            Confidence.Confirmed, "tesla.com/es_es", "https://www.tesla.com/es_es/model3/design",
            validUntil: TeslaOffersEnd),
        Fin("tesla-santander-model-y", "Tesla / Santander (Model Y)", FinancingType.Manufacturer,
            tin: 2.49m, tae: 2.52m, RepaymentStructure.Balloon, "60 mies.", "9 100 € (przykład)",
            "Rata końcowa (balon) 13 923 €", monthly: 349, interest: 2872,
            "Realnie tanie, ale tylko na Model Y (40 760 €) — poza budżetem",
            Confidence.Confirmed, "tesla.com/es_es", "https://www.tesla.com/es_es/modely/design",
            validUntil: TeslaOffersEnd),
        Fin("byd-ca-auto-bank", "BYD / CA Auto Bank", FinancingType.Manufacturer,
            tin: 3.20m, tae: 3.40m, RepaymentStructure.Linear, "min. 72 mies.",
            // 60-month example figures derived from the TIN (the promo's own
            // 72-month installment cannot describe the 26k/60m column).
            "Min. 15 000 € finansowane", "Min. 36 mies. trwania umowy", monthly: 470, interest: 2170,
            "Weź, by odblokować rabat 5k+ €, potem spłać wcześniej (max 1% kary)",
            Confidence.Estimated, "byd.com/es", "https://www.byd.com/es",
            validUntil: BydOffersEnd),
        Fin("mg-santander-open-bank", "MG / Santander–Open Bank", FinancingType.Manufacturer,
            tin: 3.50m, tae: 3.75m, RepaymentStructure.Linear, "Zmienny", "Zmienna",
            "Ograniczenia koloru/stocku", monthly: 473, interest: 2375,
            "Ta sama strategia co przy BYD",
            Confidence.Estimated, "mg.es", "https://www.mg.es"),
        Fin("omoda-santander-open-bank", "Omoda / Santander–Open Bank", FinancingType.Manufacturer,
            tin: 3.60m, tae: 3.85m, RepaymentStructure.Linear, "Zmienny", "Zmienna",
            "Min. 36 mies. trwania umowy", monthly: 474, interest: 2450,
            "Ta sama strategia co przy BYD",
            Confidence.Estimated, "omodajaecoo.es", "https://www.omodajaecoo.es"),
        Fin("toyota-easy", "Toyota Easy", FinancingType.Manufacturer,
            tin: 7.60m, tae: 7.90m, RepaymentStructure.Balloon, "Struktura balonowa", "Zmienna",
            "Standardowe", monthly: 560, interest: 5200,
            "Tylko jeśli cenisz dołączoną 4-letnią gwarancję/serwis",
            Confidence.Confirmed, "toyota.es", "https://www.toyota.es/financiacion"),
        Fin("renault-preference", "Renault Preference", FinancingType.Manufacturer,
            tin: 7.50m, tae: 10.00m, RepaymentStructure.Balloon, "Zmienny", "Zmienna",
            "Wysokie TAE względem TIN", monthly: 555, interest: 5100,
            "Porównaj dokładnie z kredytem bankowym",
            Confidence.Confirmed, "renault.es", "https://www.renault.es/financiacion.html"),
        Fin("bbva-coche-standard", "BBVA Coche (standard)", FinancingType.Bank,
            tin: 6.55m, tae: 7.41m, RepaymentStructure.Linear, "do 8 lat", "Zmienna",
            "Standardowe", monthly: 540, interest: 4900,
            "Sprawdź wariant 'Ecológico' powyżej — jest wyraźnie tańszy",
            Confidence.Confirmed, "bbva.es", "https://www.bbva.es/personas/prestamos/coche.html"),
        Fin("revel-renting", "REVEL (renting)", FinancingType.Subscription,
            tin: null, tae: null, RepaymentStructure.Subscription, "12–36 mies.", "Brak",
            "Brak", monthly: 300, interest: null,
            "Lider rynku 2026 wg COPE/Comparaturenting — 100% online, od <300€/mies.",
            Confidence.Confirmed, "revel.es", "https://www.revel.es"),
        Fin("movere-subskrypcja", "Movere (subskrypcja)", FinancingType.Subscription,
            tin: null, tae: null, RepaymentStructure.Subscription, "1–48 mies.", "Brak",
            "Brak", monthly: 340, interest: null,
            "Elastyczność, krótki horyzont, obecność w Alicante",
            Confidence.Confirmed, "movere.es", "https://www.movere.es"),
        Fin("yomovo-renting", "Yomovo (renting)", FinancingType.Subscription,
            tin: null, tae: null, RepaymentStructure.Subscription, "24–60 mies.", "Brak",
            "Brak", monthly: 313, interest: null,
            "Przejrzyste ceny od 257€/mies. dla mniejszych modeli",
            Confidence.Confirmed, "yomovo.es", "https://www.yomovo.es"),
        Fin("bipi-subskrypcja", "Bipi (subskrypcja)", FinancingType.Subscription,
            tin: null, tae: null, RepaymentStructure.Subscription, "1–48 mies.", "Brak",
            "Brak", monthly: 350, interest: null,
            "Ogólnokrajowo, bez budowania kapitału",
            Confidence.Confirmed, "bipicar.com", "https://www.bipicar.com"),
        Fin("free2move-subskrypcja", "Free2Move (subskrypcja)", FinancingType.Subscription,
            tin: null, tae: null, RepaymentStructure.Subscription, "1–48 mies.", "Brak",
            "Brak", monthly: 355, interest: null,
            "Ogólnokrajowo, bez budowania kapitału",
            Confidence.Confirmed, "free2move.com", "https://www.free2move.com/es-ES"),
    ];

    private static CarOffer Car(
        string slug, string name, string variant, DgtLabel label, int powerCv,
        decimal? cash, decimal? financed, int? reliability, string reliabilityText, int? boot,
        string notes, Confidence priceConfidence, string sourceName, string sourceUrl,
        DateTimeOffset? validUntil = null, DateTimeOffset? published = null) => new()
        {
            Slug = slug,
            Name = name,
            Variant = variant,
            DgtLabel = label,
            PowerCv = powerCv,
            CashPriceEur = cash,
            FinancedPriceEur = financed,
            ReliabilityScore = reliability,
            ReliabilityText = reliabilityText,
            BootLiters = boot,
            Notes = notes,
            PriceConfidence = priceConfidence,
            SourceName = sourceName,
            SourceUrl = sourceUrl,
            LastVerifiedAt = VerifiedAugust24,
            OfferValidUntil = validUntil,
            SourcePublishedAt = published ?? VerifiedAugust24,
            CreatedAt = VerifiedAugust24,
            UpdatedAt = VerifiedAugust24,
        };

    private static FinancingOffer Fin(
        string slug, string provider, FinancingType type,
        decimal? tin, decimal? tae, RepaymentStructure structure, string term, string down,
        string fees, decimal? monthly, decimal? interest, string bestFor,
        Confidence rateConfidence, string sourceName, string sourceUrl,
        DateTimeOffset? validUntil = null, DateTimeOffset? published = null) => new()
        {
            Slug = slug,
            Provider = provider,
            Type = type,
            TinPercent = tin,
            TaePercent = tae,
            RepaymentStructure = structure,
            TermDescription = term,
            DownPaymentDescription = down,
            FeesDescription = fees,
            MonthlyInstallment60Eur = monthly,
            TotalInterest60Eur = interest,
            BestFor = bestFor,
            RateConfidence = rateConfidence,
            SourceName = sourceName,
            SourceUrl = sourceUrl,
            LastVerifiedAt = VerifiedAugust24,
            OfferValidUntil = validUntil,
            SourcePublishedAt = published ?? VerifiedAugust24,
            CreatedAt = VerifiedAugust24,
            UpdatedAt = VerifiedAugust24,
        };
}
